path_classifiers:
    # include test files in analysis
    test:
        - exclude: tests
    docs:
        - docs
    notebooks:
        - notebooks
    versioneer:
        - prolif/_version.py
        - versioneer.py
extraction:
    python:
        index:
            exclude:
                - prolif/_version.py
                - versioneer.py
