path_classifiers:
    test:
        - exclude: tests
    docs:
        - docs
    notebooks:
        - notebooks
extraction:
    python:
        index:
            include:
                - prolif
                - tests
            exclude:
                - versioneer.py
                - prolif/_version.py