name: build-package
on:
    workflow_call:
      inputs:
        test-files:
          default: true
          required: false
          type: boolean
        test-imports:
          default: false
          required: false
          type: boolean
        cache-package:
          default: true
          required: false
          type: boolean
        upload-package:
          default: false
          required: false
          type: boolean

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    name: Build ProLIF package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup UV
      uses: astral-sh/setup-uv@v7

    - name: Adjust version based on tag
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          TAG=${GITHUB_REF#refs/*/}
          sed -i -e "s/0.0.0/${TAG#v}/" pyproject.toml
        fi

    - name: Build package
      run: |
        uv build
    
    - name: List output
      run: |
        ls -lah dist/*

    - name: List .tar.gz content
      run: |
        tar -ztvf dist/prolif-*.tar.gz
    
    - name: Ensure tests and data included in source dist
      if: inputs.test-files
      run: |
        tar -ztvf dist/prolif-*.tar.gz | grep -E 'prolif-.+/prolif/py.typed' || exit 1
        tar -ztvf dist/prolif-*.tar.gz | grep -E 'prolif-.+/tests/.+' || exit 1
        tar -ztvf dist/prolif-*.tar.gz | grep -E 'prolif-.+/tests/conftest.py' || exit 1
        tar -ztvf dist/prolif-*.tar.gz | grep -E 'prolif-.+/tests/plotting/.+' || exit 1
        tar -ztvf dist/prolif-*.tar.gz | grep -E 'prolif-.+/data/.+' || exit 1
        tar -ztvf dist/prolif-*.tar.gz | grep -E 'prolif-.+/data/vina/.+' || exit 1
        tar -ztvf dist/prolif-*.tar.gz | grep -E 'prolif-.+/prolif/plotting/network/network.html' || exit 1
        tar -ztvf dist/prolif-*.tar.gz | grep -E 'prolif-.+/prolif/plotting/network/network.css' || exit 1
        tar -ztvf dist/prolif-*.tar.gz | grep -E 'prolif-.+/prolif/plotting/network/network.js' || exit 1

    - name: Cache package
      if: inputs.cache-package
      uses: actions/cache/save@v3
      with:
        path: |
          dist/prolif-*.whl
          dist/prolif-*.tar.gz
        key: prolif-${{ runner.os }}-${{ github.sha }}

    - name: Expose package as artifact
      if: inputs.upload-package
      uses: actions/upload-artifact@v4
      with:
        name: prolif-package
        path: |
          dist/prolif-*.whl
          dist/prolif-*.tar.gz
        if-no-files-found: error
        retention-days: 20

  test-build:
    name: Test ProLIF build
    runs-on: ubuntu-latest
    needs: [build]
    if: (inputs.test-imports) && (inputs.cache-package)

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install python with pip
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"
    
    - name: Install requirements
      run: |
        pip install rdkit

    - name: Retrieve cached package
      uses: actions/cache/restore@v3
      id: cache-prolif
      with:
        path: |
          dist/prolif-*.whl
          dist/prolif-*.tar.gz
        key: prolif-${{ runner.os }}-${{ github.sha }}
    
    - name: Install from tar.gz
      run: |
        pip install dist/prolif-*.tar.gz

    - name: Test tar.gz install
      working-directory: scripts/
      run: |
        python test_build.py

    - name: Remove previous ProLIF install
      run: |
        pip uninstall -y prolif

    - name: Install from wheel
      run: |
        pip install dist/prolif-*.whl

    - name: Test wheel install
      working-directory: scripts/
      run: |
        python test_build.py