name: build-package
on:
    workflow_call:
      inputs:
        test-files:
          default: true
          required: false
          type: boolean
        test-imports:
          default: false
          required: false
          type: boolean
        cache-package:
          default: true
          required: false
          type: boolean
        upload-package:
          default: false
          required: false
          type: boolean

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    name: Build ProLIF package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Setup UV
      uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7

    - name: Adjust version based on tag
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          TAG=${GITHUB_REF#refs/*/}
          sed -i -e "s/0.0.0/${TAG#v}/" pyproject.toml
          echo "Version detected as ${TAG#v}"
        fi

    - name: Build package
      run: |
        uv build
    
    - name: List output
      run: |
        ls -lah dist/*

    - name: List .tar.gz content
      run: |
        tar -ztvf dist/prolif-*.tar.gz
    
    - name: Ensure tests and data included in source dist
      if: inputs.test-files
      run: |
        tar -ztvf dist/prolif-*.tar.gz | grep -E 'prolif-.+/prolif/py.typed' || exit 1
        tar -ztvf dist/prolif-*.tar.gz | grep -E 'prolif-.+/tests/.+' || exit 1
        tar -ztvf dist/prolif-*.tar.gz | grep -E 'prolif-.+/tests/conftest.py' || exit 1
        tar -ztvf dist/prolif-*.tar.gz | grep -E 'prolif-.+/tests/plotting/.+' || exit 1
        tar -ztvf dist/prolif-*.tar.gz | grep -E 'prolif-.+/data/.+' || exit 1
        tar -ztvf dist/prolif-*.tar.gz | grep -E 'prolif-.+/data/vina/.+' || exit 1
        tar -ztvf dist/prolif-*.tar.gz | grep -E 'prolif-.+/prolif/plotting/network/network.html' || exit 1
        tar -ztvf dist/prolif-*.tar.gz | grep -E 'prolif-.+/prolif/plotting/network/network.css' || exit 1
        tar -ztvf dist/prolif-*.tar.gz | grep -E 'prolif-.+/prolif/plotting/network/network.js' || exit 1

    - name: Cache package
      if: inputs.cache-package
      uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: |
          dist/prolif-*.whl
          dist/prolif-*.tar.gz
        key: prolif-${{ runner.os }}-${{ github.sha }}-${{ github.ref_type }}

    - name: Expose package as artifact
      if: inputs.upload-package
      uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7
      with:
        name: prolif-package
        path: |
          dist/prolif-*.whl
          dist/prolif-*.tar.gz
        if-no-files-found: error
        retention-days: 20

  test-build:
    name: Test ProLIF build
    runs-on: ubuntu-latest
    needs: [build]
    if: (inputs.test-imports) && (inputs.cache-package)

    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

    - name: Install python with pip
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
      with:
        python-version: "3.10"
        cache: "pip"
    
    - name: Install requirements
      run: |
        pip install rdkit

    - name: Retrieve cached package
      uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      id: cache-prolif
      with:
        path: |
          dist/prolif-*.whl
          dist/prolif-*.tar.gz
        key: prolif-${{ runner.os }}-${{ github.sha }}-${{ github.ref_type }}
    
    - name: Install from tar.gz
      run: |
        pip install dist/prolif-*.tar.gz

    - name: Test tar.gz install
      working-directory: scripts/
      run: |
        python test_build.py

    - name: Remove previous ProLIF install
      run: |
        pip uninstall -y prolif

    - name: Install from wheel
      run: |
        pip install dist/prolif-*.whl

    - name: Test wheel install
      working-directory: scripts/
      run: |
        python test_build.py